version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: location-service/Dockerfile
    container_name: location-service
    ports:
      - 8080:8080
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge