spring:
  application:
    name: shipment-tracker
  flyway:
    locations: classpath:/db/migration
    schemas: shipment-tracker
    baselineOnMigrate: true
    enabled: true
    hibernate:
      ddl-auto: update
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

database-details:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/shipment-tracker
  userName: postgres
  password: sourabh

logging:
  level:
    org:
      springframework:
          security: TRACE
          web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always

application:
  security:
    jwt:
      jwt-secret-key: afe65bcd93be0f27d04415f68b9b6ca33f909553ad54c3966cd719a7e44606c1
      jwt-expiration-time: 6000000  #100 min

