scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']

#
#  docker run --name prometheus -d -p 9090:9090 -v C:\Users\soura\Personal Projects\shipment-tracker\shipment-tracker\src\main\resources\prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

# or create a docker compose file