server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/soura/repo
          repos:
            development:
              pattern:
              - '*/dev'
              - '*/test'
              uri: file:///C:/Users/soura/repo/test
            production:
              pattern:
              - '*/uat'
              - '*/prod'
              uri: file:///C:/Users/soura/repo/prod
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: "*"